"""Task families and their explicit construction registry."""

from . import (
    classification,
    contrastive_tension,
    distillation,
    guided,
    late_interaction,
    mega_batch,
    modifiers,
    pairwise,
    reconstruction,
    regularization,
    retrieval,
    triplet,
)
from .config import LossConfig, LossModifierConfig, TaskConfig
from .registry import (
    BUILTIN_LOSS_MODIFIERS,
    BUILTIN_LOSSES,
    BUILTIN_TASKS,
    LossDefinition,
    LossModifierDefinition,
    LossModifierRegistry,
    LossRegistry,
    TaskDefinition,
    TaskRegistry,
    build_task,
)

__all__ = [
    "BUILTIN_LOSS_MODIFIERS",
    "BUILTIN_LOSSES",
    "BUILTIN_TASKS",
    "LossConfig",
    "LossDefinition",
    "LossModifierConfig",
    "LossModifierDefinition",
    "LossModifierRegistry",
    "LossRegistry",
    "TaskDefinition",
    "TaskConfig",
    "TaskRegistry",
    "build_task",
    "classification",
    "contrastive_tension",
    "distillation",
    "guided",
    "late_interaction",
    "mega_batch",
    "modifiers",
    "pairwise",
    "regularization",
    "reconstruction",
    "retrieval",
    "triplet",
]
