"""Generated semantic model-family registry.

Generated by ``scripts/generate_model_families.py`` from the reviewed manifest.
This file contains identifiers and contracts, not model implementation source.
Do not edit it by hand.
"""

import json

ARCHITECTURE_CATALOG_SHA256 = (
    "2af65737162af25c40803b987355fb09d4547d922842edeeb6c0f80838f4117c"
)
FAMILY_MANIFEST_SHA256 = (
    "8d13f1da622edf3b34e62e3922c78507736c41d7d66d5a56b6105f2fe1933c41"
)

MODEL_FAMILY_ROWS = json.loads(
    '[{"acceptance_gates":["config_mapping","checkpoint_roundtrip","forward",'
    '"input_gradient","performance"],"checkpoint_adapter":"representax.models'
    '.modernvbert.ModernVBERTCheckpointAdapter","checkpoint_layout":"huggingf'
    'ace_safetensors","components":["token_embedding","rotary_attention","sli'
    'ding_attention","gated_mlp","siglip_vision","pixel_shuffle_connector","m'
    'ean_pooling","l2_normalization"],"config_adapter":"representax.models.mo'
    'dernvbert.ModernVBERTConfig.from_hf_config","implementation_module":"rep'
    'resentax.models.modernvbert","input_contracts":[["text",["input_ids","at'
    'tention_mask"]],["fused",["input_ids","attention_mask","pixel_values","i'
    'mage_valid"]]],"modalities":["text","image","fused"],"model_types":["mod'
    'ernvbert"],"name":"modernvbert","output_contracts":["last_hidden_state",'
    '"mean_pooled_l2_normalized_representation"],"support":"verified"}]'
)
