"""Generated semantic model-family registry.

Generated by ``scripts/generate_model_families.py`` from the reviewed manifest.
This file contains identifiers and contracts, not model implementation source.
Do not edit it by hand.
"""

import json

ARCHITECTURE_CATALOG_SHA256 = (
    "2af65737162af25c40803b987355fb09d4547d922842edeeb6c0f80838f4117c"
)
FAMILY_MANIFEST_SHA256 = (
    "3efe9c086171f82f1b756716a3495fe0634f32104b2c8a53c19d70b859220c4c"
)

MODEL_FAMILY_ROWS = json.loads(
    '[{"acceptance_gates":["config_mapping","checkpoint_roundtrip","forward",'
    '"input_gradient","parameter_gradient","optimizer_update","export_reload"'
    ',"performance"],"checkpoint_adapter":"representax.models.bert.BertCheckp'
    'ointAdapter","checkpoint_layout":"huggingface_safetensors","components":'
    '["token_embedding","absolute_position_embedding","token_type_embedding",'
    '"multi_head_attention","post_norm_residual","dense_mlp","pooler","mean_p'
    'ooling","l2_normalization"],"config_adapter":"representax.models.bert.Be'
    'rtConfig.from_hf_config","configuration_constraints":["is_decoder=false"'
    ',"add_cross_attention=false"],"implementation_module":"representax.model'
    's.bert","input_contracts":[["text",["input_ids","attention_mask"]],["emb'
    'edded_text",["inputs_embeds","attention_mask"]]],"modalities":["text"],"'
    'model_types":["bert"],"name":"bert","output_contracts":["last_hidden_sta'
    'te","pooler_output","mean_pooled_l2_normalized_representation"],"support'
    '":"native"},{"acceptance_gates":["config_mapping","checkpoint_roundtrip"'
    ',"forward"],"checkpoint_adapter":"representax.models.jina_v5.JinaV5TextC'
    'heckpointAdapter","checkpoint_layout":"huggingface_safetensors","compone'
    'nts":["token_embedding","causal_grouped_query_attention","rotary_positio'
    'n_embedding","query_key_rms_normalization","swiglu_mlp","last_token_pool'
    'ing","matryoshka_truncation","l2_normalization"],"config_adapter":"repre'
    'sentax.models.jina_v5.JinaV5TextConfig.from_hf_config","configuration_co'
    'nstraints":["checkpoint=jina-embeddings-v5-omni-small-retrieval","revisi'
    'on=12949877f0092093f366c6450340011320152a05","text_path_only=true"],"imp'
    'lementation_module":"representax.models.jina_v5","input_contracts":[["te'
    'xt",["input_ids","attention_mask"]]],"modalities":["text"],"model_types"'
    ':["qwen3_vl_text"],"name":"jina_v5","output_contracts":["last_hidden_sta'
    'te","last_token_l2_normalized_representation"],"support":"native"},{"acc'
    'eptance_gates":["config_mapping","checkpoint_roundtrip","forward","input'
    '_gradient","performance"],"checkpoint_adapter":"representax.models.moder'
    'nvbert.ModernVBERTCheckpointAdapter","checkpoint_layout":"huggingface_sa'
    'fetensors","components":["token_embedding","rotary_attention","sliding_a'
    'ttention","gated_mlp","siglip_vision","pixel_shuffle_connector","mean_po'
    'oling","l2_normalization"],"config_adapter":"representax.models.modernvb'
    'ert.ModernVBERTConfig.from_hf_config","configuration_constraints":[],"im'
    'plementation_module":"representax.models.modernvbert","input_contracts":'
    '[["text",["input_ids","attention_mask"]],["text_image",["input_ids","att'
    'ention_mask","pixel_values","image_valid"]]],"modalities":["text","image'
    '"],"model_types":["modernvbert"],"name":"modernvbert","output_contracts"'
    ':["last_hidden_state","mean_pooled_l2_normalized_representation"],"suppo'
    'rt":"verified"},{"acceptance_gates":["config_mapping","checkpoint_roundt'
    'rip","forward","input_gradient","parameter_gradient","optimizer_update",'
    '"export_reload","performance"],"checkpoint_adapter":"representax.models.'
    'mpnet.MPNetCheckpointAdapter","checkpoint_layout":"huggingface_safetenso'
    'rs","components":["token_embedding","padding_aware_absolute_position_emb'
    'edding","bucketed_relative_attention_bias","multi_head_attention","post_'
    'norm_residual","dense_mlp","pooler","mean_pooling","l2_normalization"],"'
    'config_adapter":"representax.models.mpnet.MPNetConfig.from_hf_config","c'
    'onfiguration_constraints":["pad_token_id=1","relative_attention_num_buck'
    'ets=32"],"implementation_module":"representax.models.mpnet","input_contr'
    'acts":[["text",["input_ids","attention_mask"]],["embedded_text",["inputs'
    '_embeds","attention_mask"]]],"modalities":["text"],"model_types":["mpnet'
    '"],"name":"mpnet","output_contracts":["last_hidden_state","pooler_output'
    '","mean_pooled_l2_normalized_representation"],"support":"verified"}]'
)
