"""Generated semantic model-family registry.

Generated by ``scripts/generate_model_families.py`` from the reviewed manifest.
This file contains identifiers and contracts, not model implementation source.
Do not edit it by hand.
"""

import json

ARCHITECTURE_CATALOG_SHA256 = (
    "2af65737162af25c40803b987355fb09d4547d922842edeeb6c0f80838f4117c"
)
FAMILY_MANIFEST_SHA256 = (
    "1a0a3552bbe3e467c892753eb6729a937ab2e448299477dc57fe17a17a11412f"
)

MODEL_FAMILY_ROWS = json.loads(
    '[{"acceptance_gates":["config_mapping","checkpoint_roundtrip","forward",'
    '"input_gradient","parameter_gradient","optimizer_update","export_reload"'
    ',"performance"],"checkpoint_adapter":"representax.models.bert.BertCheckp'
    'ointAdapter","checkpoint_layout":"huggingface_safetensors","components":'
    '["token_embedding","absolute_position_embedding","token_type_embedding",'
    '"multi_head_attention","post_norm_residual","dense_mlp","pooler","mean_p'
    'ooling","l2_normalization"],"config_adapter":"representax.models.bert.Be'
    'rtConfig.from_hf_config","configuration_constraints":["is_decoder=false"'
    ',"add_cross_attention=false"],"implementation_module":"representax.model'
    's.bert","input_contracts":[["text",["input_ids","attention_mask"]],["emb'
    'edded_text",["inputs_embeds","attention_mask"]]],"modalities":["text"],"'
    'model_types":["bert"],"name":"bert","output_contracts":["last_hidden_sta'
    'te","pooler_output","mean_pooled_l2_normalized_representation"],"support'
    '":"native"},{"acceptance_gates":["config_mapping","checkpoint_roundtrip"'
    ',"forward","input_gradient","performance"],"checkpoint_adapter":"represe'
    'ntax.models.modernvbert.ModernVBERTCheckpointAdapter","checkpoint_layout'
    '":"huggingface_safetensors","components":["token_embedding","rotary_atte'
    'ntion","sliding_attention","gated_mlp","siglip_vision","pixel_shuffle_co'
    'nnector","mean_pooling","l2_normalization"],"config_adapter":"representa'
    'x.models.modernvbert.ModernVBERTConfig.from_hf_config","configuration_co'
    'nstraints":[],"implementation_module":"representax.models.modernvbert","'
    'input_contracts":[["text",["input_ids","attention_mask"]],["fused",["inp'
    'ut_ids","attention_mask","pixel_values","image_valid"]]],"modalities":["'
    'text","image","fused"],"model_types":["modernvbert"],"name":"modernvbert'
    '","output_contracts":["last_hidden_state","mean_pooled_l2_normalized_rep'
    'resentation"],"support":"verified"},{"acceptance_gates":["config_mapping'
    '","checkpoint_roundtrip","forward","input_gradient","parameter_gradient"'
    ',"optimizer_update","export_reload","performance"],"checkpoint_adapter":'
    '"representax.models.mpnet.MPNetCheckpointAdapter","checkpoint_layout":"h'
    'uggingface_safetensors","components":["token_embedding","padding_aware_a'
    'bsolute_position_embedding","bucketed_relative_attention_bias","multi_he'
    'ad_attention","post_norm_residual","dense_mlp","pooler","mean_pooling","'
    'l2_normalization"],"config_adapter":"representax.models.mpnet.MPNetConfi'
    'g.from_hf_config","configuration_constraints":["pad_token_id=1","relativ'
    'e_attention_num_buckets=32"],"implementation_module":"representax.models'
    '.mpnet","input_contracts":[["text",["input_ids","attention_mask"]],["emb'
    'edded_text",["inputs_embeds","attention_mask"]]],"modalities":["text"],"'
    'model_types":["mpnet"],"name":"mpnet","output_contracts":["last_hidden_s'
    'tate","pooler_output","mean_pooled_l2_normalized_representation"],"suppo'
    'rt":"verified"}]'
)
