"""Generate the pinned, Torch-free Transformers architecture catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

REFERENCE_VERSION = "5.3.0"
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "src/representax/integrations/_transformers_5_3_0.py"


def _rows() -> tuple[tuple[str, str, str, tuple[str, ...]], ...]:
    import transformers
    from transformers.models.auto.configuration_auto import (
        CONFIG_MAPPING_NAMES,
        model_type_to_module_name,
    )
    from transformers.models.auto.modeling_auto import MODEL_MAPPING_NAMES

    if transformers.__version__ != REFERENCE_VERSION:
        raise RuntimeError(
            f"catalog requires Transformers {REFERENCE_VERSION}, "
            f"found {transformers.__version__}"
        )

    rows = []
    for model_type, config_class in sorted(CONFIG_MAPPING_NAMES.items()):
        model_classes = MODEL_MAPPING_NAMES.get(model_type, ())
        if isinstance(model_classes, str):
            model_classes = (model_classes,)
        rows.append(
            (
                model_type,
                model_type_to_module_name(model_type),
                config_class,
                tuple(model_classes),
            )
        )
    return tuple(rows)


def _render(rows: tuple[tuple[str, str, str, tuple[str, ...]], ...]) -> str:
    payload = json.dumps(rows, separators=(",", ":"), ensure_ascii=True)
    digest = hashlib.sha256(payload.encode()).hexdigest()
    entries = "\n".join(_render_row(row) for row in rows)
    return f'''"""Generated architecture names from Transformers {REFERENCE_VERSION}.

Generated by ``scripts/generate_transformers_catalog.py``. This file contains
upstream identifiers, not model implementation source. Do not edit it by hand.
"""

TRANSFORMERS_VERSION = {json.dumps(REFERENCE_VERSION)}
CATALOG_SHA256 = {json.dumps(digest)}

ARCHITECTURE_ROWS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
{entries}
)
'''


def _render_row(row: tuple[str, str, str, tuple[str, ...]]) -> str:
    model_type, module, config_class, model_classes = row
    rendered_models = ", ".join(json.dumps(value) for value in model_classes)
    if len(model_classes) == 1:
        rendered_models += ","
    return "\n".join(
        (
            "    (",
            f"        {json.dumps(model_type)},",
            f"        {json.dumps(module)},",
            f"        {json.dumps(config_class)},",
            f"        ({rendered_models}),",
            "    ),",
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = _render(_rows())
    if arguments.check:
        if not TARGET.is_file() or TARGET.read_text() != rendered:
            raise SystemExit(f"catalog is stale: run {Path(__file__).name}")
        return
    TARGET.write_text(rendered)


if __name__ == "__main__":
    main()
