"""Native model implementations and integrations."""

from .adapters import (
    QuantizedLoRALinear,
    apply_quantized_lora,
    lora_parameter_filter,
    merge_quantized_lora,
)
from .bert import BertBatch, BertCheckpointAdapter, BertConfig, BertEncoder
from .components import (
    Activation,
    AttentionImplementation,
    LayerNorm,
    Linear,
    activate,
    dot_product_attention,
    dropout,
    embedding_lookup,
    l2_normalize,
    mean_pool,
    rematerialize,
)
from .composition import (
    DenoisingAutoEncoder,
    EncoderPair,
    PairClassifier,
    ReconstructionDecoder,
    TokenReconstructionDecoder,
)
from .dense import DenseEncoder
from .jina_v5 import (
    JINA_V5_SMALL_MODEL_ID,
    JINA_V5_SMALL_REVISION,
    JinaV5TextBatch,
    JinaV5TextCheckpointAdapter,
    JinaV5TextConfig,
    JinaV5TextEncoder,
)
from .modernvbert import (
    ModernVBERTBatch,
    ModernVBERTCheckpointAdapter,
    ModernVBERTConfig,
    ModernVBERTEncoder,
    ModernVBERTTextBatch,
    ModernVBERTTextCheckpointAdapter,
    ModernVBERTTextConfig,
    ModernVBERTTextEncoder,
)
from .mpnet import (
    MPNET_MODEL_ID,
    MPNetBatch,
    MPNetCheckpointAdapter,
    MPNetConfig,
    MPNetEncoder,
    create_mpnet_position_ids,
    mpnet_relative_position_bucket,
    mpnet_weight_names,
)
from .sentence import (
    POOLING_MODES,
    DenseActivation,
    PoolingMode,
    SentenceBatch,
    SentenceDense,
    SentenceEncoder,
    SentenceNormalize,
    SentencePooling,
)

__all__ = [
    "Activation",
    "AttentionImplementation",
    "BertBatch",
    "BertCheckpointAdapter",
    "BertConfig",
    "BertEncoder",
    "DenseEncoder",
    "DenoisingAutoEncoder",
    "EncoderPair",
    "LayerNorm",
    "Linear",
    "JINA_V5_SMALL_MODEL_ID",
    "JINA_V5_SMALL_REVISION",
    "JinaV5TextBatch",
    "JinaV5TextCheckpointAdapter",
    "JinaV5TextConfig",
    "JinaV5TextEncoder",
    "ModernVBERTBatch",
    "ModernVBERTCheckpointAdapter",
    "ModernVBERTConfig",
    "ModernVBERTEncoder",
    "ModernVBERTTextBatch",
    "ModernVBERTTextCheckpointAdapter",
    "ModernVBERTTextConfig",
    "ModernVBERTTextEncoder",
    "MPNET_MODEL_ID",
    "MPNetBatch",
    "MPNetCheckpointAdapter",
    "MPNetConfig",
    "MPNetEncoder",
    "POOLING_MODES",
    "DenseActivation",
    "PoolingMode",
    "PairClassifier",
    "QuantizedLoRALinear",
    "ReconstructionDecoder",
    "SentenceBatch",
    "SentenceDense",
    "SentenceEncoder",
    "SentenceNormalize",
    "SentencePooling",
    "TokenReconstructionDecoder",
    "activate",
    "apply_quantized_lora",
    "create_mpnet_position_ids",
    "dot_product_attention",
    "dropout",
    "embedding_lookup",
    "l2_normalize",
    "lora_parameter_filter",
    "mean_pool",
    "merge_quantized_lora",
    "mpnet_relative_position_bucket",
    "mpnet_weight_names",
    "rematerialize",
]
